"""Regenerate the paper's result tables directly from results/*.json.

This is the generator whose absence let the manuscript's numbers drift from the code. Every
table below is a pure function of the released result JSONs, so running this after any
experiment re-run keeps tables == code. Real-Wikipedia is included from its released,
in-repo result card.

Usage: ``python scripts/make_paper_tables.py`` (writes overleaf_src/tables/*.tex).
"""

from __future__ import annotations

import json
import os
from decimal import Decimal, ROUND_HALF_UP

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "results")
TAB = os.path.join(ROOT, "overleaf_src", "tables")

DETECT = [
    ("freshrag", "FreshRAG"),
    ("realworld", "Real-world"),
    ("wikidata", "Wikidata"),
    ("templama", "TempLAMA"),
    ("wikidata_prose", "Wikidata-prose"),
    ("realwiki", "Real-Wikipedia"),
]
ABLATE = DETECT[:-1]
CASE_OVERRIDES = {"realwiki": 12}
AUTO = "% Auto-generated by scripts/make_paper_tables.py -- do not edit by hand.\n"
ROW_END = r" \\"


def _fmt3(value: float) -> str:
    return str(Decimal(str(value)).quantize(Decimal("0.001"), rounding=ROUND_HALF_UP))


def _load(name: str) -> dict:
    with open(os.path.join(RES, name), encoding="utf-8") as fh:
        return json.load(fh)


def _write(fname: str, body: str) -> None:
    os.makedirs(TAB, exist_ok=True)
    with open(os.path.join(TAB, fname), "w", encoding="utf-8") as fh:
        fh.write(AUTO + body)
    print("wrote", fname)


def table1_detection() -> None:
    rows = []
    for key, disp in DETECT:
        d = _load(f"detection_{key}.json")
        ci = d.get("f1_ci95") or {}
        cases = ci.get("n_cases", CASE_OVERRIDES.get(key, d.get("n_gold_superseded", 0)))
        cistr = (f"[{_fmt3(ci['ci95_low'])}, {_fmt3(ci['ci95_high'])}]"
                 if "ci95_low" in ci else "--")
        rows.append(
            f"{disp} & {cases} & {_fmt3(d['precision'])} & {_fmt3(d['recall'])} "
            f"& {_fmt3(d['f1'])} & {cistr}" + ROW_END
        )
    body = (
        "\\begin{table}[t]\n\\centering\n\\scriptsize\n"
        "\\begin{tabular}{@{}l@{\\hspace{2.2pt}}r@{\\hspace{2.2pt}}r@{\\hspace{2.2pt}}r@{\\hspace{2.2pt}}r@{\\hspace{2.2pt}}r@{}}\n\\toprule\n"
        "Benchmark & Cases & P & R & F1 & 95\\% CI \\\\\n\\midrule\n"
        + "\n".join(rows) +
        "\n\\bottomrule\n\\end{tabular}\n"
        "\\caption{Text-driven supersession detection (single non-positional detector, "
        "Algorithm~\\ref{alg:supersession}). P/R/F1 are span-level; CIs are cluster bootstraps "
        "over cases. Every value is regenerated from \\texttt{results/detection\\_*.json}.}\n"
        "\\label{tab:detection}\n\\end{table}\n"
    )
    _write("table1_detection.tex", body)


def table3_ablation() -> None:
    cols = ["full", "-subject", "-value", "-recency", "-all"]
    rows = []
    for key, disp in ABLATE:
        a = _load(f"ablation_{key}.json")["f1"]
        cells = [f"\\textbf{{{_fmt3(a['full'])}}}"] + [_fmt3(a[c]) for c in cols[1:]]
        rows.append(f"{disp} & " + " & ".join(cells) + " \\\\")
    body = (
        "\\begin{table}[t]\n\\centering\n\\small\n"
        "\\begin{tabular}{@{}l@{\\hspace{2.5pt}}r@{\\hspace{2.5pt}}r@{\\hspace{2.5pt}}r@{\\hspace{2.5pt}}r@{\\hspace{2.5pt}}r@{}}\n\\toprule\n"
        "Benchmark & Full & $-$subject & $-$value & $-$recency & $-$all \\\\\n\\midrule\n"
        + "\n".join(rows) +
        "\n\\bottomrule\n\\end{tabular}\n"
        "\\caption{Ablation of the detector's three signals (span-level F1). Recency is the "
        "backbone everywhere; subject matching is essential on multi-entity corpora, while the "
        "value gate mainly guards FreshRAG. Randomised conditions ($-$recency, $-$all) average "
        "5 seeds. Source: \\texttt{results/ablation\\_*.json}.}\n"
        "\\label{tab:ablation}\n\\end{table}\n"
    )
    _write("table3_ablation.tex", body)


def table4_retrieval() -> None:
    order = [("freshrag", "FreshRAG"), ("wikidata", "Wikidata"), ("templama", "TempLAMA")]
    conds = [("flat", "Flat RAG"), ("lifecycle", "\\ours{}"), ("gold", "Gold (oracle)")]
    data = {k: _load(f"retrieval_{k}.json")["conditions"] for k, _ in order}

    def cell(k: str, cond: str, metric: str) -> str:
        return _fmt3(data[k][cond][metric])

    lines = []
    for cond, disp in conds:
        parts = []
        for k, _ in order:
            parts += [cell(k, cond, "SER"), cell(k, cond, "AEP")]
        bold = "\\textbf{" if cond == "lifecycle" else ""
        end = "}" if cond == "lifecycle" else ""
        # bold the AEP for the ours row
        if cond == "lifecycle":
            parts = [p if i % 2 == 0 else f"\\textbf{{{p}}}" for i, p in enumerate(parts)]
        lines.append(f"{disp} & " + " & ".join(parts) + " \\\\")
    header = (" & \\multicolumn{2}{c}{FreshRAG} & \\multicolumn{2}{c}{Wikidata} & "
              "\\multicolumn{2}{c}{TempLAMA} \\\\\n"
              " & SER & AEP & SER & AEP & SER & AEP \\\\")
    body = (
        "\\begin{table}[t]\n\\centering\n\\footnotesize\n"
        "\\begin{tabular}{@{}l@{\\hspace{2.0pt}}r@{\\hspace{2.0pt}}r@{\\hspace{3.5pt}}r@{\\hspace{2.0pt}}r@{\\hspace{3.5pt}}r@{\\hspace{2.0pt}}r@{}}\n\\toprule\n" + header + "\n\\midrule\n"
        + "\n".join(lines) +
        "\n\\bottomrule\n\\end{tabular}\n"
        "\\caption{Lifecycle-aware retrieval drives stale-evidence rate (SER, lower better) "
        "to $\\approx0$ and lifts active-evidence precision (AEP, higher better) to the "
        "oracle, with no gold labels at inference. Source: \\texttt{results/retrieval\\_*.json}.}\n"
        "\\label{tab:retrieval}\n\\end{table}\n"
    )
    _write("table4_retrieval.tex", body)


def table2_judge(judge_model: str = "gpt-4o-mini") -> None:
    j = _load(f"judge_wikidata_{judge_model}.json")
    h, lj = j["heuristic"], j["llm_judge"]
    body = (
        "\\begin{table}[t]\n\\centering\n\\footnotesize\n"
        "\\begin{tabular}{@{}l@{\\hspace{2.5pt}}l@{\\hspace{2.5pt}}r@{\\hspace{2.5pt}}r@{\\hspace{2.5pt}}r@{}}\n\\toprule\n"
        "Benchmark & Method & P & R & F1 \\\\\n\\midrule\n"
        "\\multirow{2}{*}{Wikidata}\n"
            f" & Heuristic (ours) & {_fmt3(h['precision'])} & {_fmt3(h['recall'])} "
            f"& \\textbf{{{_fmt3(h['f1'])}}} \\\\\n"
            f" & LLM judge (\\texttt{{{judge_model}}}) & {_fmt3(lj['precision'])} & {_fmt3(lj['recall'])} "
            f"& {_fmt3(lj['f1'])} \\\\\n"
        "\\bottomrule\n\\end{tabular}\n"
        f"\\caption{{The zero-LLM heuristic vs a prompted \\texttt{{{judge_model}}} judge on the "
        "identical Wikidata span pairs ($240$ pairs, $120$ positive), at no inference cost. "
        "Source: the released Wikidata judge card.}\n"
        "\\label{tab:llm_baseline}\n\\end{table}\n"
    )
    _write("table2_llm_baseline.tex", body)


def table6_money() -> None:
    datasets = (("wikidata", "Wikidata", 33), ("templama", "TempLAMA", 300))
    readers = (("extractive", "Ext."), ("qwen", "Qwen"))
    methods = (
        ("flat", "Flat RAG"),
        ("tempralm", "TempRALM"),
        ("ragtime_tuned", "RAG-Time"),
        ("lifecycle", "\\textbf{\\ours{}}"),
        ("gold", "Gold oracle"),
    )
    cards = {
        (dataset, reader): _load(f"qa_{dataset}_{reader}.json")
        for dataset, _display, _n in datasets
        for reader, _reader_display in readers
    }

    rows = []
    for method, display in methods:
        cells = []
        for dataset, _dataset_display, _n in datasets:
            for reader, _reader_display in readers:
                value = cards[(dataset, reader)]["current_answer_em"][method]
                cell = _fmt3(value)
                if method == "lifecycle":
                    cell = f"\\textbf{{{cell}}}"
                cells.append(cell)
        rows.append(f"{display} & " + " & ".join(cells) + " \\\\")

    body = (
        "\\begin{table}[t]\n\\centering\n\\footnotesize\n"
        "\\begin{tabular}{@{}l@{\\hspace{2.5pt}}r@{\\hspace{2.5pt}}r@{\\hspace{2.5pt}}r@{\\hspace{2.5pt}}r@{}}\n"
        "\\toprule\n"
        " & \\multicolumn{2}{c}{Wikidata ($n{=}33$)} "
        "& \\multicolumn{2}{c}{TempLAMA ($n{=}300$)} \\\\\n"
        "Method & Ext. & Qwen & Ext. & Qwen \\\\\n\\midrule\n"
        + "\n".join(rows) +
        "\n\\bottomrule\n\\end{tabular}\n"
        "\\caption{Current-answer exact match (EM) under a direct head-to-head: each method "
        "receives the identical corpus, question, five-claim budget, prompt, reader, and scoring. "
        "TempRALM and RAG-Time alter only retrieval; RAG-Time uses the development-selected "
        "$(\\alpha,h){=}(0.7,1825\\,\\mathrm{days})$ setting. Source: "
        "the four released \\texttt{results/qa*} cards.}\n"
        "\\label{tab:money}\n\\end{table}\n"
    )
    _write("table6_money.tex", body)


if __name__ == "__main__":
    table1_detection()
    table3_ablation()
    table4_retrieval()
    try:
        table2_judge()
    except FileNotFoundError as e:
        print("skip table2 (judge result not found yet):", e)
    try:
        table6_money()
    except FileNotFoundError as e:
        print("skip table6 (QA result not found yet):", e)
